import { GoogleGenAI, Chat, Type, GenerateContentResponse } from "@google/genai";

const getAIClient = (apiKey: string) => {
  return new GoogleGenAI({ apiKey });
};

// Timeout Wrapper
const withTimeout = <T>(promise: Promise<T>, ms: number = 25000): Promise<T> => {
    return Promise.race([
        promise,
        new Promise<T>((_, reject) => 
            setTimeout(() => reject(new Error("Request timed out. Please try again.")), ms)
        )
    ]);
};

export const generateHint = async (title: string, description: string, apiKey: string): Promise<string> => {
  if (!apiKey) throw new Error("API_KEY_MISSING");
  const ai = getAIClient(apiKey);
  try {
    const response = await withTimeout(ai.models.generateContent({
      model: 'gemini-3-flash-preview',
      contents: `Context: The user is solving the coding problem "${title}".\nProblem Description: ${description}\n\nTask: Provide a cryptic but helpful hint that nudges the user in the right direction without revealing the full solution. Be concise.`,
    })) as GenerateContentResponse;
    return response.text || "Could not generate hint.";
  } catch (error: any) {
    console.error("AI Error", error);
    throw error;
  }
};

export const autoGenerateTitle = async (url: string, apiKey: string): Promise<string> => {
  if (!apiKey) throw new Error("API_KEY_MISSING");
  const ai = getAIClient(apiKey);
  try {
    const response = await withTimeout(ai.models.generateContent({
      model: 'gemini-3-flash-preview',
      contents: `Extract the likely coding problem title from this URL. Return ONLY the title text, nothing else. URL: ${url}`,
    })) as GenerateContentResponse;
    return response.text?.trim() || "";
  } catch (error) {
    return "";
  }
};

export const autoGenerateDescription = async (title: string, apiKey: string): Promise<string> => {
  if (!apiKey) throw new Error("API_KEY_MISSING");
  const ai = getAIClient(apiKey);
  try {
      const response = await withTimeout(ai.models.generateContent({
          model: 'gemini-3-flash-preview',
          contents: `Provide a competitive programming description for "${title}". Include Input/Output format. No solution. Return in Markdown format.`
      })) as GenerateContentResponse;
      return response.text || "";
  } catch (error) {
      console.error("AI Error", error);
      throw error;
  }
};

export const expandDescription = async (title: string, currentDesc: string, apiKey: string): Promise<string> => {
  if (!apiKey) throw new Error("API_KEY_MISSING");
  const ai = getAIClient(apiKey);
  try {
      const response = await withTimeout(ai.models.generateContent({
          model: 'gemini-3-flash-preview',
          contents: `The following coding problem description for "${title}" is too short. Expand it by adding clear constraints and 2 concrete examples (Input/Output). Keep the core task same. Return in Markdown. Current: "${currentDesc}"`
      })) as GenerateContentResponse;
      return response.text || currentDesc;
  } catch (error) {
      return currentDesc;
  }
};

export const findProblemUrl = async (title: string, apiKey: string): Promise<string> => {
    if (!apiKey) throw new Error("API_KEY_MISSING");
    const ai = getAIClient(apiKey);
    
    // Helper to extract URL from text
    const extractUrl = (text: string) => {
        const match = text.match(/https?:\/\/[^\s]+|www\.[^\s]+/);
        if (!match) return "";
        let url = match[0];
        url = url.replace(/[.,;)]$/, "");
        if (!url.startsWith('http')) url = 'https://' + url;
        return url;
    };

    try {
      const response = await withTimeout(ai.models.generateContent({
        model: 'gemini-3-flash-preview',
        contents: `Find the official LeetCode or GeeksForGeeks URL for the coding problem "${title}". Return ONLY the URL.`,
        config: {
            tools: [{googleSearch: {}}]
        }
      })) as GenerateContentResponse;
      const text = response.text?.trim() || "";
      const url = extractUrl(text);
      if (url) return url;
    } catch (error) {
      console.warn("Grounding search failed, falling back to knowledge base", error);
    }

    try {
        const response = await withTimeout(ai.models.generateContent({
            model: 'gemini-3-flash-preview',
            contents: `What is the URL for the LeetCode problem "${title}"? Return ONLY the URL.`,
        })) as GenerateContentResponse;
        const text = response.text?.trim() || "";
        return extractUrl(text);
    } catch (error) {
        console.error("URL Lookup Error", error);
        return "";
    }
};

export const analyzeSolution = async (code: string, title: string, description: string, apiKey: string): Promise<string> => {
  if (!apiKey) throw new Error("API_KEY_MISSING");
  const ai = getAIClient(apiKey);
  try {
    const response = await withTimeout(ai.models.generateContent({
      model: 'gemini-3-flash-preview',
      contents: `Act as a helpful coding interview coach.\n\nProblem Title: ${title}\nProblem Description: ${description}\n\nUser's Code:\n\`\`\`\n${code}\n\`\`\`\n\n1. If the code is empty, give a high-level approach hint based on the problem description.\n2. If partial, suggest the next step.\n3. If complete, analyze Time/Space complexity and suggest ONE improvement.\n\nKeep it concise (max 3 sentences), encouraging, and use Markdown.`,
    })) as GenerateContentResponse;
    return response.text || "";
  } catch (error) {
    return "Analysis unavailable";
  }
};

export const generateEdgeCases = async (title: string, description: string, apiKey: string): Promise<string> => {
  if (!apiKey) throw new Error("API_KEY_MISSING");
  const ai = getAIClient(apiKey);
  try {
    const response = await withTimeout(ai.models.generateContent({
      model: 'gemini-3-flash-preview',
      contents: `Based on this problem "${title}", list 3 critical edge cases (e.g., empty input, max value).
      Format: Return ONLY a bulleted list in Markdown. Be extremely concise.
      Description: ${description}`,
    })) as GenerateContentResponse;
    return response.text || "";
  } catch (error) {
    console.error("AI Error", error);
    throw error;
  }
};

export const generateTestCases = async (title: string, description: string, apiKey: string): Promise<any[]> => {
    if (!apiKey) throw new Error("API_KEY_MISSING");
    const ai = getAIClient(apiKey);
    try {
        const response = await withTimeout(ai.models.generateContent({
            model: 'gemini-3-flash-preview',
            contents: `Generate 3 diverse test cases for the problem "${title}". 
            Description: ${description}
            
            Return a JSON array where each object has:
            - input: A JSON string representing the arguments array (e.g. "[[1,2], 3]")
            - expected: A JSON string representing the return value (e.g. "3")
            `,
            config: {
                responseMimeType: "application/json",
                responseSchema: {
                    type: Type.ARRAY,
                    items: {
                        type: Type.OBJECT,
                        properties: {
                            input: { type: Type.STRING },
                            expected: { type: Type.STRING }
                        }
                    }
                }
            }
        })) as GenerateContentResponse;
        
        return JSON.parse(response.text || "[]");
    } catch (error) {
        console.error("Gen Test Cases Error", error);
        return [];
    }
};

export const generatePracticeQuestions = async (
    count: number, 
    difficulty: string, 
    topics: string[], 
    customQuery: string,
    apiKey: string
): Promise<any[]> => {
    if (!apiKey) throw new Error("API_KEY_MISSING");
    const ai = getAIClient(apiKey);
    
    const topicStr = topics.includes('Random') ? 'random data structures and algorithms' : topics.join(', ');
    const userPrompt = customQuery ? `USER CUSTOM REQUEST (High Priority): "${customQuery}". Ignore topic/difficulty standard if this request conflicts.` : '';
    
    try {
        const response = await withTimeout(ai.models.generateContent({
            model: 'gemini-3-flash-preview',
            contents: `Generate ${count} unique coding interview questions.
            ${userPrompt}
            Context: Difficulty ${difficulty}, Topics: ${topicStr}.
            
            CRITICAL OUTPUT REQUIREMENTS:
            1. "description": Must be a VERBOSE Markdown string (minimum 100 words). 
               - Start with "### Problem Statement".
               - Use "**" only for key terms, do NOT bold the entire text.
               - MUST Include a "### Example" section with Input/Output code blocks.
               - MUST Include "### Constraints" as a bulleted list.
            2. "url": Provide the actual LeetCode or GeeksForGeeks URL. If not found, leave it as an empty string.
            3. "title": The standard name of the problem.
            4. "testCases": Array of 2 basic test cases (input/expected strings).
            
            Return valid JSON array.`,
            config: {
                responseMimeType: "application/json",
                responseSchema: {
                    type: Type.ARRAY,
                    items: {
                        type: Type.OBJECT,
                        properties: {
                            title: { type: Type.STRING },
                            description: { type: Type.STRING },
                            difficulty: { type: Type.STRING },
                            topics: { type: Type.ARRAY, items: { type: Type.STRING } },
                            url: { type: Type.STRING },
                            testCases: { 
                                type: Type.ARRAY,
                                items: {
                                    type: Type.OBJECT,
                                    properties: {
                                        input: { type: Type.STRING },
                                        expected: { type: Type.STRING }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }), 30000) as GenerateContentResponse; 

        const text = response.text || "[]";
        return JSON.parse(text);
    } catch (error) {
        console.error("Question Gen Error", error);
        throw error;
    }
};

export const createChatSession = (apiKey: string): Chat => {
  if (!apiKey) throw new Error("API_KEY_MISSING");
  const ai = new GoogleGenAI({ apiKey });
  return ai.chats.create({
    model: 'gemini-3-flash-preview',
    config: {
      systemInstruction: 'You are a helpful coding assistant. You can help debug code, explain concepts, and provide hints.',
    }
  });
};