import React, { useState } from 'react';
import { X, Sparkles, Wand2, Loader2, CheckCircle2, Plus, Search } from 'lucide-react';
import { generatePracticeQuestions } from '../services/geminiService';
import { Question } from '../types';
import { safeUUID } from '../utils/helpers';
import Button from './Button';

interface AIQuestionGeneratorModalProps {
    isOpen: boolean;
    onClose: () => void;
    onImport: (questions: Question[]) => void;
    showToast: (msg: string, type: string, undo: any) => void;
    apiKey: string;
}

const TOPICS_LIST = ["Arrays", "Strings", "Hash Map", "Linked List", "Trees", "Graphs", "DP", "Heap", "Binary Search", "Two Pointers"];

const AIQuestionGeneratorModal: React.FC<AIQuestionGeneratorModalProps> = ({ isOpen, onClose, onImport, showToast, apiKey }) => {
    const [step, setStep] = useState<'config' | 'loading' | 'preview'>('config');
    const [count, setCount] = useState(3);
    const [difficulty, setDifficulty] = useState('Medium');
    const [selectedTopics, setSelectedTopics] = useState<string[]>(['Random']);
    const [customPrompt, setCustomPrompt] = useState('');
    const [generatedQuestions, setGeneratedQuestions] = useState<any[]>([]);
    const [selectedForImport, setSelectedForImport] = useState<Set<number>>(new Set());

    const toggleTopic = (t: string) => {
        if (t === 'Random') {
            setSelectedTopics(['Random']);
            return;
        }
        
        let newTopics = selectedTopics.filter(x => x !== 'Random');
        if (newTopics.includes(t)) {
            newTopics = newTopics.filter(x => x !== t);
        } else {
            newTopics.push(t);
        }
        
        if (newTopics.length === 0) newTopics = ['Random'];
        setSelectedTopics(newTopics);
    };

    const handleGenerate = async () => {
        if (!apiKey) {
            showToast("API Key missing. Please check Settings.", "error", null);
            return;
        }

        setStep('loading');
        try {
            const rawQuestions = await generatePracticeQuestions(count, difficulty, selectedTopics, customPrompt, apiKey);
            if (Array.isArray(rawQuestions) && rawQuestions.length > 0) {
                setGeneratedQuestions(rawQuestions);
                // Select all by default
                setSelectedForImport(new Set(rawQuestions.map((_, i) => i)));
                setStep('preview');
            } else {
                throw new Error("No questions returned");
            }
        } catch (error: any) {
            setStep('config');
            if (error.message.includes('timeout')) {
                showToast("Request timed out. Try fewer questions.", "error", null);
            } else {
                showToast("Failed to generate. Check API Key.", "error", null);
            }
        }
    };

    const handleImport = () => {
        const toImport: Question[] = generatedQuestions
            .filter((_, i) => selectedForImport.has(i))
            .map(raw => {
                // Fallback URL if AI fails to provide a specific one
                const fallbackUrl = `https://www.google.com/search?q=${encodeURIComponent(raw.title + ' leetcode')}`;
                
                return {
                    id: safeUUID(),
                    title: raw.title || "Untitled Problem",
                    // Ensure description is populated or provides a default message. 
                    // Stricter check: > 100 characters to ensure it's not a stub.
                    description: raw.description && raw.description.length > 100 
                        ? raw.description 
                        : `### ${raw.title}\n\n*Description not fully generated by AI.*\n\nPlease use the "Expand" or "Auto-Fill" feature in the editor to fetch full details.`,
                    difficulty: (['Easy', 'Medium', 'Hard'].includes(raw.difficulty) ? raw.difficulty : difficulty) as any,
                    topics: Array.isArray(raw.topics) ? raw.topics : selectedTopics.filter(t => t !== 'Random'),
                    status: 'Todo',
                    url: raw.url && raw.url.startsWith('http') ? raw.url : fallbackUrl,
                    hints: [],
                    solutions: [],
                    notes: '',
                    mistakes: '',
                    timeTaken: 0,
                    lastAttempted: null,
                    testCases: Array.isArray(raw.testCases) ? raw.testCases : []
                };
            });
        
        onImport(toImport);
        onClose();
        // Reset state
        setStep('config');
        setGeneratedQuestions([]);
        setCustomPrompt('');
    };

    if (!isOpen) return null;

    return (
        <div className="fixed inset-0 z-[60] flex items-center justify-center bg-black/60 backdrop-blur-sm p-4 animate-in fade-in duration-200">
            <div className="bg-white/95 backdrop-blur-xl border border-white/40 shadow-2xl rounded-2xl w-full max-w-2xl overflow-hidden flex flex-col max-h-[90vh]">
                
                {/* Header */}
                <div className="p-6 border-b border-slate-100 flex justify-between items-center bg-slate-50/50">
                    <div className="flex items-center gap-2">
                        <div className="p-2 bg-gradient-to-tr from-indigo-500 to-purple-500 rounded-lg text-white">
                            <Sparkles size={20} />
                        </div>
                        <h2 className="text-xl font-bold text-slate-800">AI Question Curator</h2>
                    </div>
                    <button onClick={onClose} className="p-2 hover:bg-slate-200 rounded-full text-slate-500 transition-colors"><X size={20}/></button>
                </div>

                {/* Body */}
                <div className="p-6 flex-1 overflow-y-auto custom-scrollbar">
                    {step === 'config' && (
                        <div className="space-y-6">
                            {/* Custom Prompt Input */}
                            <div className="space-y-2">
                                <label className="text-sm font-bold text-slate-600 flex items-center gap-2">
                                    <Search size={14} /> Custom Request (Optional)
                                </label>
                                <textarea 
                                    value={customPrompt} 
                                    onChange={(e) => setCustomPrompt(e.target.value)}
                                    placeholder="e.g. 'Blind 75 questions about Linked Lists' or 'Top Google interview questions 2024'"
                                    className="w-full p-3 text-sm bg-slate-50 border border-slate-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-indigo-500/20 focus:border-indigo-500 transition-all resize-none h-20 placeholder:text-slate-400"
                                />
                            </div>

                            <div className="space-y-2">
                                <label className="text-sm font-bold text-slate-600">How many questions?</label>
                                <div className="flex gap-2">
                                    {[1, 2, 3, 4, 5].map(n => (
                                        <button 
                                            key={n}
                                            onClick={() => setCount(n)}
                                            className={`flex-1 py-2 rounded-lg font-bold text-sm border transition-all ${count === n ? 'bg-indigo-600 text-white border-indigo-600' : 'bg-white text-slate-600 border-slate-200 hover:border-indigo-300'}`}
                                        >
                                            {n}
                                        </button>
                                    ))}
                                </div>
                            </div>

                            <div className="space-y-2">
                                <label className="text-sm font-bold text-slate-600">Difficulty Level</label>
                                <div className="grid grid-cols-3 gap-2">
                                    {['Easy', 'Medium', 'Hard'].map(d => (
                                        <button 
                                            key={d}
                                            onClick={() => setDifficulty(d)}
                                            className={`py-2 rounded-lg font-bold text-sm border transition-all ${difficulty === d ? 'bg-indigo-600 text-white border-indigo-600' : 'bg-white text-slate-600 border-slate-200 hover:border-indigo-300'}`}
                                        >
                                            {d}
                                        </button>
                                    ))}
                                </div>
                            </div>

                            <div className="space-y-2">
                                <label className="text-sm font-bold text-slate-600">Topics</label>
                                <div className="flex flex-wrap gap-2">
                                    <button 
                                        onClick={() => toggleTopic('Random')}
                                        className={`px-3 py-1.5 rounded-full text-xs font-bold border transition-all ${selectedTopics.includes('Random') ? 'bg-purple-100 text-purple-700 border-purple-200' : 'bg-white text-slate-500 border-slate-200'}`}
                                    >
                                        🎲 Random
                                    </button>
                                    {TOPICS_LIST.map(t => (
                                        <button 
                                            key={t}
                                            onClick={() => toggleTopic(t)}
                                            className={`px-3 py-1.5 rounded-full text-xs font-bold border transition-all ${selectedTopics.includes(t) ? 'bg-indigo-100 text-indigo-700 border-indigo-200' : 'bg-white text-slate-500 border-slate-200 hover:border-indigo-300'}`}
                                        >
                                            {t}
                                        </button>
                                    ))}
                                </div>
                            </div>
                        </div>
                    )}

                    {step === 'loading' && (
                        <div className="flex flex-col items-center justify-center py-12 space-y-4">
                            <div className="relative">
                                <div className="absolute inset-0 bg-indigo-500 blur-xl opacity-20 rounded-full animate-pulse"></div>
                                <Loader2 size={48} className="text-indigo-600 animate-spin relative z-10" />
                            </div>
                            <p className="text-slate-600 font-medium animate-pulse">Curating your practice set...</p>
                            <div className="text-xs text-slate-400">Finding high-quality problems based on your criteria</div>
                        </div>
                    )}

                    {step === 'preview' && (
                        <div className="space-y-3">
                            <div className="flex justify-between items-center mb-2">
                                <p className="text-sm text-slate-500">Select questions to add:</p>
                                <button 
                                    onClick={() => setSelectedForImport(selectedForImport.size === generatedQuestions.length ? new Set() : new Set(generatedQuestions.map((_, i) => i)))}
                                    className="text-xs font-bold text-indigo-600 hover:underline"
                                >
                                    {selectedForImport.size === generatedQuestions.length ? 'Deselect All' : 'Select All'}
                                </button>
                            </div>
                            {generatedQuestions.map((q, i) => (
                                <div 
                                    key={i} 
                                    onClick={() => {
                                        const newSet = new Set(selectedForImport);
                                        if (newSet.has(i)) newSet.delete(i);
                                        else newSet.add(i);
                                        setSelectedForImport(newSet);
                                    }}
                                    className={`p-4 rounded-xl border cursor-pointer transition-all flex items-start gap-3 group ${selectedForImport.has(i) ? 'bg-indigo-50 border-indigo-200 ring-1 ring-indigo-500/20' : 'bg-white border-slate-200 hover:border-indigo-200 hover:bg-slate-50'}`}
                                >
                                    <div className={`mt-1 w-5 h-5 rounded-full border flex items-center justify-center shrink-0 transition-colors ${selectedForImport.has(i) ? 'bg-indigo-600 border-indigo-600 text-white' : 'border-slate-300 bg-white group-hover:border-indigo-300'}`}>
                                        {selectedForImport.has(i) && <CheckCircle2 size={12} />}
                                    </div>
                                    <div className="flex-1 min-w-0">
                                        <div className="flex justify-between items-start">
                                            <h4 className="font-bold text-slate-800 text-sm truncate pr-2">{q.title}</h4>
                                            {q.url && <a href={q.url} target="_blank" rel="noreferrer" onClick={e => e.stopPropagation()} className="text-slate-300 hover:text-indigo-500"><Search size={14} /></a>}
                                        </div>
                                        <div className="flex gap-2 mt-1 mb-2">
                                            <span className="text-[10px] font-bold px-1.5 py-0.5 bg-white border rounded text-slate-500">{q.difficulty}</span>
                                            {q.topics?.slice(0,2).map((t: string) => <span key={t} className="text-[10px] px-1.5 py-0.5 bg-slate-100 rounded text-slate-500">{t}</span>)}
                                        </div>
                                        <p className="text-xs text-slate-500 line-clamp-2">{q.description?.replace(/[#*`]/g, '').substring(0, 120)}...</p>
                                    </div>
                                </div>
                            ))}
                        </div>
                    )}
                </div>

                {/* Footer */}
                <div className="p-6 border-t border-slate-100 bg-slate-50/50 flex justify-end gap-3">
                    {step === 'config' && (
                        <>
                            <button onClick={onClose} className="px-4 py-2 text-slate-500 font-bold text-sm hover:bg-slate-200 rounded-lg transition-colors">Cancel</button>
                            <Button onClick={handleGenerate} icon={<Wand2 size={16}/>}>Find Questions</Button>
                        </>
                    )}
                    {step === 'preview' && (
                        <>
                            <button onClick={() => setStep('config')} className="px-4 py-2 text-slate-500 font-bold text-sm hover:bg-slate-200 rounded-lg transition-colors">Back</button>
                            <Button onClick={handleImport} icon={<Plus size={16}/>} disabled={selectedForImport.size === 0}>
                                Import {selectedForImport.size} Questions
                            </Button>
                        </>
                    )}
                </div>
            </div>
        </div>
    );
};

export default AIQuestionGeneratorModal;