import React, { useState, useEffect, useRef } from 'react';
import { Question, Solution, TestCase, TestResult } from '../types';
import { 
    X, Plus, Wand2, Trash2, Save,
    Layout, Code2, StickyNote, ExternalLink, 
    RotateCcw, Search, Pencil, Check, 
    ChevronDown, 
    Loader2,
    Expand,
    BrainCircuit,
    PlayCircle,
    BookOpen,
    GripVertical,
    GripHorizontal,
    AlertTriangle,
    ShieldAlert,
    Timer,
    Play,
    ChevronUp,
    Terminal,
    ArrowLeft
} from 'lucide-react';
import CodeEditor from './CodeEditor';
import MarkdownView from './MarkdownView';
import Console from './Console';
import { executeCode } from '../utils/codeRunner';
import { generateHint, autoGenerateTitle, analyzeSolution, findProblemUrl, autoGenerateDescription, expandDescription, generateTestCases, generateEdgeCases } from '../services/geminiService';
import { calculateEfficiency, calculateNextReview, formatTime, formatTimeAgo, getDifficultyColor } from '../utils/helpers';

// Styles
const modalBaseStyle = "bg-slate-900 border border-white/10 shadow-2xl";
const footerStyle = "bg-slate-900/50 backdrop-blur-md border-t border-white/5";

interface ModalProps {
  isOpen: boolean;
  onClose: () => void;
  question: Question;
  onSave: (q: Question) => void;
  onDelete: (id: string) => void;
  onStartTimer: (currentTime: number) => void;
  onAddSessionTime?: (seconds: number) => void;
  showToast: (msg: string, type: string, undo: any) => void;
  apiKey: string;
  liveTime?: number;
}

const QuestionModal: React.FC<ModalProps> = ({ 
    isOpen, onClose, question: initialQuestion, onSave, onDelete, onStartTimer, onAddSessionTime, showToast, apiKey, liveTime 
}) => {
  const [data, setData] = useState<Question>(initialQuestion);
  const [activeTab, setActiveTab] = useState<'details' | 'solutions' | 'notes'>('details');
  const [activeSolIndex, setActiveSolIndex] = useState(0);
  
  const [aiStatus, setAiStatus] = useState<string | null>(null);
  const [manualHintInput, setManualHintInput] = useState('');
  const [isAddingHint, setIsAddingHint] = useState(false);
  const [isCoachCollapsed, setIsCoachCollapsed] = useState(false);
  
  // Mobile Mode State
  const [mobileReadOnly, setMobileReadOnly] = useState(true);

  // Split View State
  const [leftPanelWidth, setLeftPanelWidth] = useState(45); // percent
  const isDraggingHorizontal = useRef(false);
  
  // Vertical Split State (Right Panel)
  const [consoleHeight, setConsoleHeight] = useState(40); // percent
  const isDraggingVertical = useRef(false);

  // Practice State
  const [testCases, setTestCases] = useState<TestCase[]>(initialQuestion.testCases || []);
  const [testResults, setTestResults] = useState<TestResult[] | null>(null);
  const [isConsoleOpen, setIsConsoleOpen] = useState(false);
  const [isRunningCode, setIsRunningCode] = useState(false);

  // Solution Edit
  const [isEditingSolTitle, setIsEditingSolTitle] = useState(false);

  // Confirmation State
  const [confirmation, setConfirmation] = useState<{
      type: 'reset' | 'delete' | 'discard' | 'deleteSolution' | 'deleteHint' | null;
      title: string;
      message: string;
      actionLabel: string;
      variant: 'danger' | 'warning';
      payload?: any;
  }>({ type: null, title: '', message: '', actionLabel: '', variant: 'danger' });
  
  const [isMobile, setIsMobile] = useState(window.innerWidth < 768);
  const [isEditingDesc, setIsEditingDesc] = useState(false);
  
  const originalStateRef = useRef<string>(JSON.stringify(initialQuestion));

  useEffect(() => {
    const handleResize = () => setIsMobile(window.innerWidth < 768);
    window.addEventListener('resize', handleResize);
    return () => window.removeEventListener('resize', handleResize);
  }, []);

  // Update local state when prop changes
  useEffect(() => {
      if (isOpen) {
          setData(initialQuestion);
          setTestCases(initialQuestion.testCases || []);
          originalStateRef.current = JSON.stringify(initialQuestion);
      }
  }, [isOpen, initialQuestion]); 

  // Sync Live Time from Timer
  useEffect(() => {
      if (liveTime !== undefined) {
          setData(prev => ({ ...prev, timeTaken: liveTime }));
      }
  }, [liveTime]);

  // Sync test cases to data
  useEffect(() => {
      setData(prev => ({ ...prev, testCases }));
  }, [testCases]);

  useEffect(() => {
    if (data.solutions.length === 0) {
        const defaultSol: Solution = {
            id: Date.now().toString(),
            title: 'Solution 1',
            code: '',
            language: 'javascript'
        };
        const newData = { ...data, solutions: [defaultSol] };
        setData(newData);
        if (initialQuestion.solutions.length === 0) {
             originalStateRef.current = JSON.stringify(newData);
        }
    }
  }, [data.solutions.length, data, initialQuestion.solutions.length]);

  // Helpers for validation state
  const isMetadataMissing = !data.title?.trim() || !data.url?.trim();
  
  const getDisabledReason = (baseReason: string) => {
      if (!data.title?.trim()) return "Disabled: Question Title is missing";
      if (!data.url?.trim()) return "Disabled: Question URL is missing";
      if (!!aiStatus) return "Disabled: AI is currently processing";
      return baseReason;
  };

  // Resizing Logic - Horizontal
  const handleMouseDownH = () => {
      isDraggingHorizontal.current = true;
      document.addEventListener('mousemove', handleMouseMoveH);
      document.addEventListener('mouseup', handleMouseUpH);
      document.body.style.cursor = 'col-resize';
      document.body.style.userSelect = 'none';
  };
  const handleMouseMoveH = (e: MouseEvent) => {
      if (!isDraggingHorizontal.current) return;
      const newWidth = (e.clientX / window.innerWidth) * 100;
      if(newWidth > 20 && newWidth < 80) setLeftPanelWidth(newWidth);
  };
  const handleMouseUpH = () => {
      isDraggingHorizontal.current = false;
      document.removeEventListener('mousemove', handleMouseMoveH);
      document.removeEventListener('mouseup', handleMouseUpH);
      document.body.style.cursor = 'default';
      document.body.style.userSelect = 'auto';
  };

  // Resizing Logic - Vertical (Right Panel)
  const handleMouseDownV = () => {
      isDraggingVertical.current = true;
      document.addEventListener('mousemove', handleMouseMoveV);
      document.addEventListener('mouseup', handleMouseUpV);
      document.body.style.cursor = 'row-resize';
      document.body.style.userSelect = 'none';
  };
  const handleMouseMoveV = (e: MouseEvent) => {
      if (!isDraggingVertical.current) return;
      const modalHeight = window.innerHeight * 0.95; // 95vh approximation
      // Calculation relative to bottom
      const newHeight = ((window.innerHeight - e.clientY) / modalHeight) * 100; 
      // Clamp between 10% and 80%
      if(newHeight > 10 && newHeight < 80) setConsoleHeight(newHeight);
  };
  const handleMouseUpV = () => {
      isDraggingVertical.current = false;
      document.removeEventListener('mousemove', handleMouseMoveV);
      document.removeEventListener('mouseup', handleMouseUpV);
      document.body.style.cursor = 'default';
      document.body.style.userSelect = 'auto';
  };

  const handleAddSolution = () => {
      const newSol: Solution = {
          id: Date.now().toString(),
          title: `Solution ${data.solutions.length + 1}`,
          code: '',
          language: 'javascript'
      };
      setData(prev => ({ ...prev, solutions: [...prev.solutions, newSol] }));
      setActiveSolIndex(data.solutions.length);
  };

  const handleDeleteSolution = () => {
      if (data.solutions.length <= 1) {
          showToast("Cannot delete the only solution.", "error", null);
          return;
      }
      setConfirmation({
          type: 'deleteSolution',
          title: 'Delete Solution',
          message: 'Are you sure you want to delete this solution? Code will be lost.',
          actionLabel: 'Delete',
          variant: 'danger'
      });
  };

  const handleRequestDeleteHint = (index: number) => {
      setConfirmation({
          type: 'deleteHint',
          title: 'Delete Hint',
          message: 'Are you sure you want to delete this hint?',
          actionLabel: 'Delete',
          variant: 'danger',
          payload: index
      });
  };

  const requestReset = () => {
      setConfirmation({
          type: 'reset',
          title: 'Reset Progress',
          message: 'This will clear your code, notes, and status. Are you sure?',
          actionLabel: 'Reset Everything',
          variant: 'danger'
      });
  };

  const updateSolutionTitle = (newTitle: string) => {
      const updatedSols = [...data.solutions];
      updatedSols[activeSolIndex].title = newTitle;
      setData({...data, solutions: updatedSols});
  };

  if (!isOpen) return null;

  const handleAIError = (e: any) => {
      setAiStatus(null);
      if (e.message === 'API_KEY_MISSING') {
          showToast("API Key missing. Please go to Settings.", "error", null);
      } else if (e.message.includes('timeout')) {
          showToast("AI Timeout. The request took too long.", "error", null);
      } else {
          showToast("AI Error: " + (e.message || "Unknown error"), "error", null);
      }
  };

  const handleSafeClose = () => {
      const currentData = { ...data, testCases };
      const currentString = JSON.stringify(currentData);
      
      if (currentString !== originalStateRef.current) {
          setConfirmation({
              type: 'discard',
              title: 'Unsaved Changes',
              message: 'You have modified this question. Discard changes and close?',
              actionLabel: 'Discard Changes',
              variant: 'danger'
          });
      } else {
          onClose();
      }
  };

  const executeConfirmation = () => {
      if (confirmation.type === 'reset') {
           setData({ ...data, status: 'Todo', timeTaken: 0, lastAttempted: null, solutions: [{ id: Date.now().toString(), title: 'Solution 1', code: '', language: 'javascript' }], hints: [], notes: '', mistakes: '', nextReviewDate: null, reviewInterval: 0 });
           setTestCases([]);
           showToast("Question reset successfully.", "success", null);
      } else if (confirmation.type === 'delete') {
           onDelete(data.id);
           onClose(); 
      } else if (confirmation.type === 'discard') {
          onClose();
      } else if (confirmation.type === 'deleteSolution') {
          const newSols = data.solutions.filter((_, i) => i !== activeSolIndex);
          setData({ ...data, solutions: newSols });
          setActiveSolIndex(Math.max(0, activeSolIndex - 1));
          showToast("Solution deleted.", "success", null);
      } else if (confirmation.type === 'deleteHint') {
          const idx = confirmation.payload;
          setData({ ...data, hints: data.hints.filter((_, i) => i !== idx) });
          showToast("Hint deleted.", "success", null);
      }
      setConfirmation({ type: null, title: '', message: '', actionLabel: '', variant: 'danger' });
  };

  const handleSaveWrapper = () => {
      let finalData = { ...data, testCases };
      // Review Logic
      const isStatusChangedToSolved = finalData.status === 'Solved' && initialQuestion.status !== 'Solved';
      const isReviewDue = finalData.status === 'Solved' && finalData.nextReviewDate && new Date(finalData.nextReviewDate) <= new Date();
      
      if (isStatusChangedToSolved || isReviewDue) {
          const efficiency = calculateEfficiency(finalData.difficulty, finalData.timeTaken);
          const srsData = calculateNextReview(finalData.reviewInterval || 0, efficiency?.grade || 'Avg');
          
          finalData = { 
              ...finalData, 
              nextReviewDate: srsData.nextDate, 
              reviewInterval: srsData.interval, 
              lastAttempted: new Date().toISOString() 
          };
          const msg = isStatusChangedToSolved ? `Marked Solved! Next review in ${srsData.interval} day(s).` : `Review Complete! Next review in ${srsData.interval} day(s).`;
          showToast(msg, "success", null);
      }
      
      onSave(finalData);
  };

  // --- Test Runner ---
  const handleRunCode = async () => {
      setIsRunningCode(true);
      setIsConsoleOpen(true); // Auto open console
      const currentSol = data.solutions[activeSolIndex];
      const currentCode = currentSol?.code || '';
      
      setTimeout(() => {
          const results = executeCode(currentCode, testCases);
          setTestResults(results);
          setIsRunningCode(false);
          
          const allPassed = results.length > 0 && results.every(r => r.passed);
          if (allPassed) showToast("All test cases passed!", "success", null);
          else showToast("Some tests failed. Check console.", "error", null);
      }, 500);
  };

  const addTestCase = () => setTestCases([...testCases, { input: '[]', expected: '""' }]);
  const updateTestCase = (index: number, field: 'input' | 'expected', value: string) => { 
      const newCases = [...testCases]; 
      newCases[index][field] = value; 
      setTestCases(newCases); 
  };
  const removeTestCase = (index: number) => setTestCases(testCases.filter((_, i) => i !== index));

  // --- AI Handlers ---
  const handleGenerateHint = async () => {
    if (!data.description) { showToast("Add description first", "error", null); return; }
    if (!apiKey) { handleAIError(new Error('API_KEY_MISSING')); return; }
    setAiStatus("Generating Hint...");
    try {
        const hint = await generateHint(data.title, data.description, apiKey);
        setData(prev => ({ ...prev, hints: [...prev.hints, hint], timeTaken: prev.timeTaken + 60 }));
        onAddSessionTime?.(60); 
        showToast("Hint generated! +1 min added.", "info", null);
    } catch(e) { handleAIError(e); }
    setAiStatus(null);
  };
  
  const handleAutoTitle = async () => {
     if(!data.url) return showToast("Enter URL first", "error", null);
     setAiStatus("Fetching Title...");
     try {
         const title = await autoGenerateTitle(data.url, apiKey);
         if(title) setData(prev => ({ ...prev, title }));
         else showToast("Could not find title", "error", null);
     } catch(e) { handleAIError(e); }
     setAiStatus(null);
  };

  const handleAutoUrl = async () => {
      if(!data.title) return showToast("Enter Title first", "error", null);
      setAiStatus("Finding URL...");
      try {
          const url = await findProblemUrl(data.title, apiKey);
          if(url) setData(prev => ({ ...prev, url }));
          else showToast("Could not find URL", "error", null);
      } catch(e) { handleAIError(e); }
      setAiStatus(null);
  };

  const handleAutoDescription = async () => {
      if(!data.title) return showToast("Enter Title first", "error", null);
      setAiStatus("Generating...");
      try {
          const desc = await autoGenerateDescription(data.title, apiKey);
          setData(prev => ({ ...prev, description: desc }));
      } catch(e) { handleAIError(e); }
      setAiStatus(null);
  };

  const handleExpandDescription = async () => {
      if(!data.description) return;
      setAiStatus("Expanding...");
      try {
          const desc = await expandDescription(data.title, data.description, apiKey);
          setData(prev => ({ ...prev, description: desc }));
      } catch(e) { handleAIError(e); }
      setAiStatus(null);
  };

  const handleGenerateEdgeCases = async () => {
      if(!data.title && !data.description) return showToast("Title or Desc required", "error", null);
      setAiStatus("Finding Edge Cases...");
      try {
          const edges = await generateEdgeCases(data.title, data.description, apiKey);
          const formatted = `\n\n**Edge Cases:**\n${edges}`;
          setData(prev => ({ ...prev, description: prev.description + formatted }));
      } catch(e) { handleAIError(e); }
      setAiStatus(null);
  };

  const handleSmartCoach = async () => { 
      const code = data.solutions[activeSolIndex]?.code;
      if (!apiKey) { handleAIError(new Error('API_KEY_MISSING')); return; }
      setAiStatus("Analyzing...");
      try {
          const analysis = await analyzeSolution(code || "// No code", data.title, data.description || "", apiKey);
          if (analysis) {
              const updatedSols = [...data.solutions];
              updatedSols[activeSolIndex].complexity = analysis;
              setData({ ...data, solutions: updatedSols });
              setIsCoachCollapsed(false);
              showToast("Coach feedback received", "success", null);
          }
      } catch (e) { handleAIError(e); }
      setAiStatus(null);
  };

  const handleGenerateTestCases = async () => {
      if (!apiKey) { handleAIError(new Error('API_KEY_MISSING')); return; }
      if (!data.title && !data.description) { showToast("Need title or description", "error", null); return; }
      setAiStatus("Generating Cases...");
      try {
          const newCases = await generateTestCases(data.title, data.description, apiKey);
          if (newCases && newCases.length > 0) {
              setTestCases(prev => [...prev, ...newCases]);
              showToast(`Added ${newCases.length} test cases`, "success", null);
          } else {
              showToast("No test cases generated", "error", null);
          }
      } catch (e) { handleAIError(e); }
      setAiStatus(null);
  };

  const ConfirmationDialog = () => (
    <div className="absolute inset-0 z-[100] flex items-center justify-center bg-black/80 backdrop-blur-sm p-4 animate-in fade-in duration-200">
        <div className="bg-slate-900 border border-white/10 p-6 rounded-xl max-w-sm w-full shadow-2xl transform scale-100 transition-all">
            <h3 className="text-lg font-bold text-white mb-2">{confirmation.title}</h3>
            <p className="text-slate-400 text-sm mb-6">{confirmation.message}</p>
            <div className="flex justify-end gap-3">
                <button 
                    onClick={() => setConfirmation({ type: null, title: '', message: '', actionLabel: '', variant: 'danger' })}
                    className="px-4 py-2 text-slate-400 hover:text-white font-bold text-sm"
                >
                    Cancel
                </button>
                <button 
                    onClick={executeConfirmation}
                    className={`px-4 py-2 rounded-lg font-bold text-sm text-white shadow-lg ${confirmation.variant === 'danger' ? 'bg-red-600 hover:bg-red-500 shadow-red-900/20' : 'bg-yellow-600 hover:bg-yellow-500'}`}
                >
                    {confirmation.actionLabel}
                </button>
            </div>
        </div>
    </div>
  );

  const HintsSection = () => (
      <div className="space-y-3 mt-6">
         <div className="flex justify-between items-center">
            <h3 className="text-sm font-bold text-slate-400 uppercase tracking-wider">Hints</h3>
            {data.description && !mobileReadOnly && (
                <button 
                    onClick={handleGenerateHint} 
                    disabled={!!aiStatus || isMetadataMissing} 
                    className="text-xs font-bold text-purple-400 hover:text-purple-300 flex items-center gap-1 disabled:opacity-50 disabled:cursor-not-allowed"
                    title={getDisabledReason("Generate a hint using AI (adds 1 min to time)")}
                >
                    {aiStatus ? <Loader2 size={12} className="animate-spin" /> : <><Wand2 size={12}/> AI Hint (+1 min)</>}
                </button>
            )}
         </div>
         <div className="space-y-2">
            {data.hints.length === 0 && <p className="text-xs text-slate-600 italic">No hints available yet.</p>}
            {data.hints.map((hint, i) => (
                <details key={i} className="group bg-yellow-500/10 border border-yellow-500/20 rounded-lg relative [&::-webkit-details-marker]:hidden">
                    <summary className="flex items-center justify-between p-3 cursor-pointer text-sm font-medium text-yellow-500 select-none list-none"><span>Hint {i + 1}</span><ChevronDown size={14} className="group-open:rotate-180 transition-transform text-yellow-500" /></summary>
                    <div className="px-3 pb-3 pt-0 text-sm text-yellow-200/80 leading-relaxed border-t border-yellow-500/20 mt-1 pr-8">{hint}</div>
                    {!mobileReadOnly && <button onClick={() => handleRequestDeleteHint(i)} className="absolute top-3 right-3 opacity-0 group-hover:opacity-100 text-slate-400 hover:text-red-500 transition-all z-10" title="Delete Hint"><Trash2 size={14} /></button>}
                </details>
            ))}
            {!mobileReadOnly && (isAddingHint ? (
                <div className="flex items-center gap-2 mt-2">
                    <input value={manualHintInput} onChange={e => setManualHintInput(e.target.value)} className="flex-1 bg-black/20 border border-slate-700 rounded-lg px-3 py-2 text-sm focus:outline-none focus:border-indigo-500 text-slate-200" placeholder="Type hint..." autoFocus />
                    <button onClick={() => { if(manualHintInput) { setData({...data, hints: [...data.hints, manualHintInput]}); setManualHintInput(''); setIsAddingHint(false); } }} className="p-2 bg-green-500/10 text-green-500 border border-green-500/20 rounded-lg" title="Save Hint"><Check size={16} /></button>
                    <button onClick={() => setIsAddingHint(false)} className="p-2 text-slate-400 hover:text-slate-200" title="Cancel"><X size={16}/></button>
                </div>
            ) : (
                <button onClick={() => setIsAddingHint(true)} className="w-full py-3 text-xs font-bold text-slate-400 bg-white/5 hover:bg-white/10 rounded-lg border border-white/5 mt-4 flex items-center justify-center gap-2" title="Manually add a hint"><Plus size={14}/> Add Hint Manually</button>
            ))}
         </div>
      </div>
  );

  // --- DESKTOP SPLIT VIEW ---
  const renderDesktopSplitView = () => (
    <div className="flex h-full overflow-hidden select-text">
        {/* LEFT PANEL: Problem Details */}
        <div className="flex flex-col border-r border-white/10 h-full bg-slate-900/50" style={{ width: `${leftPanelWidth}%` }}>
            <div className="flex-1 overflow-y-auto p-6 custom-scrollbar space-y-6">
                
                {/* Header Inputs */}
                <div className="space-y-4">
                    <div className="flex items-center gap-2">
                         <input 
                            value={data.title} 
                            onChange={e => setData({...data, title: e.target.value})} 
                            className="flex-1 bg-transparent text-xl font-bold text-white placeholder-white/20 focus:outline-none border-b border-transparent focus:border-indigo-500 transition-colors" 
                            placeholder="Problem Title" 
                        />
                        <button 
                            onClick={handleAutoUrl} 
                            disabled={!data.title || !!aiStatus} 
                            title={!data.title ? "Disabled: Enter a title first" : "Find URL using AI"}
                            className="p-2 bg-indigo-500/10 text-indigo-400 hover:bg-indigo-500/20 rounded-lg transition-colors disabled:opacity-30 disabled:cursor-not-allowed"
                        >
                            <Search size={14}/>
                        </button>
                    </div>
                    
                    <div className="flex gap-2">
                        <input 
                            value={data.url || ''} 
                            onChange={e => setData({...data, url: e.target.value})} 
                            className="flex-1 bg-white/5 border border-white/10 rounded-lg px-3 py-2 text-xs text-indigo-300 focus:outline-none focus:border-indigo-500/50" 
                            placeholder="Problem URL" 
                        />
                         <button 
                            onClick={handleAutoTitle} 
                            disabled={!data.url || !!aiStatus}
                            title={!data.url ? "Disabled: Enter a URL first" : "Fetch Title using AI"}
                            className="p-2 bg-indigo-500/10 text-indigo-400 hover:bg-indigo-500/20 rounded-lg transition-colors disabled:opacity-30 disabled:cursor-not-allowed"
                        >
                            <Wand2 size={14}/>
                         </button>
                         {data.url && (
                            <a href={data.url} target="_blank" rel="noreferrer" className="p-2 bg-white/5 rounded-lg text-slate-400 hover:text-white transition-colors" title="Open Link">
                                <ExternalLink size={14} />
                            </a>
                        )}
                    </div>
                </div>

                {/* Metadata */}
                <div className="grid grid-cols-2 gap-4">
                     <div className="space-y-1">
                         <label className="text-[10px] font-bold text-slate-500 uppercase">Difficulty</label>
                         <select 
                            value={data.difficulty} 
                            onChange={e => setData({...data, difficulty: e.target.value as any})} 
                            className="w-full bg-white/5 border border-white/10 rounded-lg px-3 py-2 text-sm font-medium text-slate-200 focus:outline-none"
                         >
                            <option className="bg-slate-900">Easy</option>
                            <option className="bg-slate-900">Medium</option>
                            <option className="bg-slate-900">Hard</option>
                         </select>
                     </div>
                     <div className="space-y-1">
                         <label className="text-[10px] font-bold text-slate-500 uppercase">Time Taken (sec)</label>
                         <div className="flex gap-2">
                             <input 
                                type="number" 
                                value={data.timeTaken} 
                                onChange={e => setData({...data, timeTaken: parseInt(e.target.value) || 0})} 
                                className="w-full bg-white/5 border border-white/10 rounded-lg px-3 py-2 text-sm font-mono text-slate-200 focus:outline-none" 
                                readOnly={liveTime !== undefined}
                             />
                             <button onClick={() => onStartTimer(data.timeTaken)} className="px-3 py-2 bg-indigo-600/20 text-indigo-300 hover:bg-indigo-600/30 border border-indigo-500/20 rounded-lg flex items-center justify-center transition-colors" title="Start Timer">
                                <Play size={14} fill="currentColor"/>
                             </button>
                         </div>
                     </div>
                </div>

                {/* Description Editor */}
                <div className="space-y-2">
                    <div className="flex justify-between items-center">
                        <label className="text-[10px] font-bold text-slate-500 uppercase">Description</label>
                        <div className="flex gap-2">
                            <button 
                                onClick={handleGenerateEdgeCases} 
                                disabled={(!data.title && !data.description) || !!aiStatus} 
                                title={(!data.title && !data.description) ? "Disabled: Needs Title or Description" : "Generate Edge Cases based on Title/Description"}
                                className="text-[10px] flex items-center gap-1 px-2 py-1 bg-amber-500/10 text-amber-400 rounded hover:bg-amber-500/20 border border-amber-500/20 disabled:opacity-50 disabled:cursor-not-allowed"
                            >
                                <ShieldAlert size={10} /> Edge Cases
                            </button>
                            <button 
                                onClick={handleExpandDescription} 
                                disabled={!data.description || !!aiStatus} 
                                title={!data.description ? "Disabled: Description is empty" : "Expand current description with more details"}
                                className="text-[10px] flex items-center gap-1 px-2 py-1 bg-blue-500/10 text-blue-400 rounded hover:bg-blue-500/20 border border-blue-500/20 disabled:opacity-50 disabled:cursor-not-allowed"
                            >
                                <Expand size={10} /> Expand
                            </button>
                            <button 
                                onClick={handleAutoDescription} 
                                disabled={!data.title || !!aiStatus} 
                                title={!data.title ? "Disabled: Title is missing" : "Auto-generate description from Title"}
                                className="text-[10px] flex items-center gap-1 px-2 py-1 bg-indigo-500/10 text-indigo-400 rounded hover:bg-indigo-500/20 border border-indigo-500/20 disabled:opacity-50 disabled:cursor-not-allowed"
                            >
                                <Wand2 size={10} /> Auto-Fill
                            </button>
                        </div>
                    </div>
                    <div onClick={() => setIsEditingDesc(true)} className={`min-h-[200px] p-4 rounded-xl border border-white/10 bg-white/5 hover:bg-white/10 transition-colors cursor-text ${isEditingDesc ? 'ring-1 ring-indigo-500/50' : ''}`}>
                         {isEditingDesc ? (
                              <textarea 
                                autoFocus 
                                value={data.description} 
                                onChange={e => setData({...data, description: e.target.value})} 
                                onBlur={() => setIsEditingDesc(false)} 
                                className="w-full h-full min-h-[180px] bg-transparent text-sm text-slate-200 outline-none resize-none font-mono" 
                                placeholder="Paste description..." 
                              />
                          ) : (
                              <div className="text-slate-200 text-sm"><MarkdownView content={data.description} /></div>
                          )}
                    </div>
                </div>

                <HintsSection />

                {/* Notes */}
                 <div className="space-y-4 pt-4 border-t border-white/5">
                     <div className="space-y-1">
                        <label className="text-[10px] font-bold text-slate-500 uppercase">Notes</label>
                        <textarea value={data.notes} onChange={e => setData({...data, notes: e.target.value})} className="w-full h-24 bg-white/5 border border-white/10 rounded-xl p-3 text-xs text-slate-300 focus:outline-none resize-none" placeholder="Notes..." />
                     </div>
                     <div className="space-y-1">
                        <label className="text-[10px] font-bold text-slate-500 uppercase text-rose-400/80">Mistakes</label>
                        <textarea value={data.mistakes} onChange={e => setData({...data, mistakes: e.target.value})} className="w-full h-24 bg-rose-500/5 border border-rose-500/10 rounded-xl p-3 text-xs text-rose-200 focus:outline-none resize-none" placeholder="Mistakes made..." />
                     </div>
                 </div>
            </div>
        </div>
        
        {/* DRAGGER (Horizontal) */}
        <div 
            onMouseDown={handleMouseDownH}
            className="w-1.5 h-full cursor-col-resize bg-slate-900 hover:bg-indigo-500 transition-colors flex items-center justify-center z-10"
        >
            <GripVertical size={12} className="text-white/20" />
        </div>

        {/* RIGHT PANEL: Editor & Console */}
        <div className="flex flex-col h-full bg-black/20" style={{ width: `${100 - leftPanelWidth}%` }}>
             {/* Toolbar */}
             <div className="h-14 border-b border-white/10 flex items-center justify-between px-4 bg-white/5 shrink-0">
                 <div className="flex items-center gap-3">
                     <div className="flex bg-black/40 rounded-lg p-0.5 border border-white/10">
                         {data.solutions.map((s, i) => (
                             <button key={s.id} onClick={() => setActiveSolIndex(i)} className={`px-3 py-1.5 rounded-md text-xs font-bold transition-all ${activeSolIndex === i ? 'bg-indigo-600 text-white' : 'text-slate-400 hover:text-white'}`}>{s.title}</button>
                         ))}
                         <button onClick={handleAddSolution} className="px-2 py-1.5 text-slate-500 hover:text-white" title="Add New Solution Variant"><Plus size={14}/></button>
                     </div>
                     {/* Solution Rename */}
                     {isEditingSolTitle ? (
                         <div className="flex items-center gap-1">
                             <input 
                                autoFocus
                                value={data.solutions[activeSolIndex]?.title}
                                onChange={(e) => updateSolutionTitle(e.target.value)}
                                onBlur={() => setIsEditingSolTitle(false)}
                                className="w-24 bg-slate-800 text-white text-xs px-2 py-1 rounded border border-indigo-500 outline-none"
                             />
                             <button onClick={() => setIsEditingSolTitle(false)} className="text-emerald-500"><Check size={12}/></button>
                         </div>
                     ) : (
                         <button onClick={() => setIsEditingSolTitle(true)} className="text-slate-500 hover:text-white" title="Rename Solution">
                             <Pencil size={12} />
                         </button>
                     )}
                     <button onClick={handleDeleteSolution} className="text-slate-500 hover:text-red-400 transition-colors" title="Delete Solution"><Trash2 size={12}/></button>
                 </div>
                 <div className="flex items-center gap-3">
                     <select value={data.solutions[activeSolIndex]?.language || 'javascript'} onChange={(e) => { const s = [...data.solutions]; s[activeSolIndex].language = e.target.value; setData({...data, solutions:s}); }} className="bg-black/40 border border-white/10 text-xs font-bold text-slate-300 rounded-lg px-3 py-1.5 focus:outline-none"><option value="javascript">JavaScript</option><option value="python">Python</option><option value="java">Java</option></select>
                     <button 
                        onClick={handleSmartCoach} 
                        disabled={!!aiStatus || isMetadataMissing} 
                        title={getDisabledReason("Get AI complexity analysis and suggestions")}
                        className="px-3 py-1.5 bg-purple-600/20 text-purple-300 border border-purple-500/30 hover:bg-purple-600/30 text-xs font-bold rounded-lg flex items-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed"
                    >
                        <BrainCircuit size={14}/> Coach
                    </button>
                    <button 
                        onClick={handleRunCode} 
                        disabled={isRunningCode || isMetadataMissing} 
                        title={getDisabledReason("Run code against test cases")}
                        className="px-3 py-1.5 bg-emerald-600 hover:bg-emerald-500 text-white text-xs font-bold rounded-lg flex items-center gap-1 transition-all shadow-lg shadow-emerald-900/20 disabled:opacity-50 disabled:cursor-not-allowed"
                    >
                        {isRunningCode ? <Loader2 size={14} className="animate-spin" /> : <PlayCircle size={14} />} Run
                    </button>
                 </div>
             </div>

             {/* Coach Feedback Overlay/Collapse */}
             {data.solutions[activeSolIndex]?.complexity && (
                <div className={`bg-purple-900/20 border-b border-purple-500/20 transition-all overflow-hidden ${isCoachCollapsed ? 'h-0' : 'max-h-40 shrink-0'}`}>
                    <div className="p-3 text-xs text-purple-200 overflow-y-auto max-h-40 relative">
                        <button onClick={() => setIsCoachCollapsed(true)} className="absolute top-2 right-2 text-purple-400 hover:text-white"><X size={12}/></button>
                        <MarkdownView content={data.solutions[activeSolIndex].complexity || ''} />
                    </div>
                </div>
             )}

             {/* Editor Area */}
             <div className="flex-1 relative min-h-0">
                  <CodeEditor 
                    code={data.solutions[activeSolIndex]?.code || ''} 
                    language={data.solutions[activeSolIndex]?.language}
                    onChange={(val) => { const newSols = [...data.solutions]; newSols[activeSolIndex].code = val; setData({...data, solutions: newSols}); }} 
                  />
             </div>

             {/* DRAGGER (Vertical) */}
             <div 
                onMouseDown={handleMouseDownV}
                className="h-1.5 w-full cursor-row-resize bg-slate-900 hover:bg-indigo-500 transition-colors flex items-center justify-center z-10 shrink-0"
             >
                <GripHorizontal size={12} className="text-white/20" />
             </div>

             {/* Bottom Panel: Test Cases & Console */}
             <div className="min-h-[100px] border-t border-white/10 flex flex-col bg-slate-900/80 backdrop-blur-xl" style={{ height: `${consoleHeight}%` }}>
                  {/* Console Header */}
                  <div className="flex items-center justify-between px-4 py-2 bg-white/5 border-b border-white/5 shrink-0">
                       <div className="flex gap-4">
                           <button onClick={() => setIsConsoleOpen(false)} className={`text-xs font-bold uppercase pb-1 border-b-2 transition-colors ${!isConsoleOpen ? 'text-white border-indigo-500' : 'text-slate-500 border-transparent hover:text-slate-300'}`}>Test Cases</button>
                           <button onClick={() => setIsConsoleOpen(true)} className={`text-xs font-bold uppercase pb-1 border-b-2 transition-colors ${isConsoleOpen ? 'text-white border-indigo-500' : 'text-slate-500 border-transparent hover:text-slate-300'}`}>Console</button>
                       </div>
                       {!isConsoleOpen && (
                           <div className="flex gap-2">
                               <button 
                                    onClick={handleGenerateTestCases} 
                                    disabled={(!data.title && !data.description) || !!aiStatus} 
                                    title={(!data.title && !data.description) ? "Disabled: Needs Title or Description" : "Generate test cases using AI"}
                                    className="text-[10px] bg-purple-500/20 text-purple-300 px-2 py-1 rounded hover:bg-purple-500/30 transition-colors border border-purple-500/20 flex items-center gap-1 disabled:opacity-50 disabled:cursor-not-allowed"
                                >
                                   {aiStatus ? <Loader2 size={10} className="animate-spin"/> : <BrainCircuit size={12}/>} AI Cases
                               </button>
                               <button onClick={addTestCase} className="text-[10px] bg-indigo-500/20 text-indigo-300 px-2 py-1 rounded hover:bg-indigo-500/30 transition-colors border border-indigo-500/20" title="Add a new test case manually">+ Add Case</button>
                           </div>
                       )}
                  </div>

                  <div className="flex-1 overflow-y-auto p-0 custom-scrollbar relative">
                      {isConsoleOpen ? (
                          <Console results={testResults} isOpen={true} onToggle={() => {}} />
                      ) : (
                          <div className="p-4 space-y-3">
                              {testCases.map((tc, idx) => (
                                  <div key={idx} className="flex gap-2 items-start group">
                                      <span className="text-xs text-slate-500 font-mono mt-2 w-4">{idx+1}</span>
                                      <div className="flex-1 space-y-2">
                                          <div className="flex flex-col">
                                              <label className="text-[10px] text-slate-500 mb-0.5">Input (JSON args)</label>
                                              <input value={tc.input} onChange={e => updateTestCase(idx, 'input', e.target.value)} className="w-full bg-black/40 border border-white/10 rounded px-2 py-1.5 text-xs font-mono text-slate-300 focus:border-indigo-500/50 focus:outline-none" placeholder="e.g. [[2,7], 9]" />
                                          </div>
                                          <div className="flex flex-col">
                                              <label className="text-[10px] text-slate-500 mb-0.5">Expected Output</label>
                                              <input value={tc.expected} onChange={e => updateTestCase(idx, 'expected', e.target.value)} className="w-full bg-black/40 border border-white/10 rounded px-2 py-1.5 text-xs font-mono text-slate-300 focus:border-indigo-500/50 focus:outline-none" placeholder="e.g. [0,1]" />
                                          </div>
                                      </div>
                                      <button onClick={() => removeTestCase(idx)} className="p-1.5 hover:bg-white/10 rounded text-slate-500 hover:text-red-400 transition-colors mt-6 opacity-0 group-hover:opacity-100" title="Remove Test Case"><X size={14}/></button>
                                  </div>
                              ))}
                              {testCases.length === 0 && <p className="text-xs text-slate-500 italic text-center mt-4">No test cases. Add one or ask AI.</p>}
                          </div>
                      )}
                  </div>
             </div>
        </div>
    </div>
  );

  // --- MOBILE VIEW ---
  const renderMobileLayout = () => {
      // 1. Mobile Header
      const MobileHeader = () => (
          <div className="flex items-center justify-between p-4 bg-slate-900 border-b border-white/10 shrink-0 z-20 shadow-lg">
               <button onClick={handleSafeClose} className="p-2 text-slate-400 hover:text-white rounded-lg hover:bg-white/5 transition-colors">
                   <ArrowLeft size={20} />
               </button>
               <h2 className="text-base font-bold text-white truncate max-w-[50%]">{data.title || "Untitled Problem"}</h2>
               <div className="flex bg-slate-800 rounded-lg p-1 border border-white/5">
                   <button 
                      onClick={() => setMobileReadOnly(true)} 
                      className={`px-3 py-1.5 rounded-md text-xs font-bold transition-all flex items-center gap-1 ${mobileReadOnly ? 'bg-indigo-600 text-white shadow' : 'text-slate-400'}`}
                   >
                       <BookOpen size={14} /> Read
                   </button>
                   <button 
                      onClick={() => setMobileReadOnly(false)} 
                      className={`px-3 py-1.5 rounded-md text-xs font-bold transition-all flex items-center gap-1 ${!mobileReadOnly ? 'bg-indigo-600 text-white shadow' : 'text-slate-400'}`}
                   >
                       <Code2 size={14} /> Code
                   </button>
               </div>
          </div>
      );

      // 2. Mobile Reading Mode (Vertical, Read-only info)
      const MobileReadingView = () => (
          <div className="flex-1 overflow-y-auto px-5 py-6 custom-scrollbar space-y-8 bg-slate-950">
              {/* Metadata Card */}
              <div className="space-y-4">
                  <div className="flex items-start justify-between">
                      <h1 className="text-2xl font-bold text-white leading-tight">{data.title || "Untitled"}</h1>
                      <span className={`px-2 py-1 rounded text-xs font-bold border uppercase tracking-wider ${getDifficultyColor(data.difficulty)}`}>{data.difficulty}</span>
                  </div>
                  <div className="flex items-center gap-4 text-xs text-slate-400">
                      <span className="flex items-center gap-1.5"><Timer size={14}/> {formatTime(data.timeTaken)}</span>
                      <span className="flex items-center gap-1.5">Last: {data.lastAttempted ? formatTimeAgo(data.lastAttempted) : 'Never'}</span>
                      <span className={`flex items-center gap-1.5 ${data.status === 'Solved' ? 'text-emerald-400' : 'text-slate-400'}`}>{data.status}</span>
                  </div>
                  {data.url && (
                      <a href={data.url} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 text-xs font-bold text-indigo-400 hover:text-indigo-300">
                          View Original Problem <ExternalLink size={12}/>
                      </a>
                  )}
              </div>

              <hr className="border-white/10" />

              {/* Description */}
              <div className="space-y-2">
                  <h3 className="text-sm font-bold text-slate-500 uppercase tracking-wider">Problem Statement</h3>
                  <div className="text-sm text-slate-300 leading-relaxed">
                      <MarkdownView content={data.description} />
                  </div>
              </div>

              {/* Hints - Only show if exist */}
              {data.hints.length > 0 && (
                  <div className="space-y-3">
                      <h3 className="text-sm font-bold text-slate-500 uppercase tracking-wider">Hints</h3>
                      <div className="space-y-2">
                          {data.hints.map((h, i) => (
                              <details key={i} className="group bg-white/5 border border-white/5 rounded-lg">
                                  <summary className="p-3 text-sm font-medium text-amber-400 cursor-pointer flex justify-between items-center">
                                      <span>Hint {i+1}</span> <ChevronDown size={14} className="group-open:rotate-180 transition-transform"/>
                                  </summary>
                                  <div className="px-3 pb-3 pt-0 text-sm text-slate-300 border-t border-white/5 mt-1">{h}</div>
                              </details>
                          ))}
                      </div>
                  </div>
              )}

              {/* Solutions - Read Only */}
              <div className="space-y-3">
                  <h3 className="text-sm font-bold text-slate-500 uppercase tracking-wider">Solutions</h3>
                  {data.solutions.map((sol, i) => (
                      <div key={sol.id} className="border border-white/10 rounded-xl overflow-hidden bg-black/20">
                          <div className="px-4 py-2 bg-white/5 border-b border-white/5 flex justify-between items-center">
                              <span className="text-xs font-bold text-white">{sol.title}</span>
                              <span className="text-[10px] uppercase text-slate-500">{sol.language}</span>
                          </div>
                          <div className="h-48 relative">
                              <CodeEditor code={sol.code} readOnly={true} onChange={()=>{}} language={sol.language} />
                          </div>
                      </div>
                  ))}
              </div>

              {/* Notes */}
              {(data.notes || data.mistakes) && (
                  <div className="space-y-4 pt-4 border-t border-white/10">
                      {data.notes && (
                          <div className="space-y-1">
                              <h4 className="text-xs font-bold text-slate-500 uppercase">My Notes</h4>
                              <p className="text-sm text-slate-300 bg-white/5 p-3 rounded-lg">{data.notes}</p>
                          </div>
                      )}
                      {data.mistakes && (
                          <div className="space-y-1">
                              <h4 className="text-xs font-bold text-rose-400/80 uppercase">Mistakes</h4>
                              <p className="text-sm text-rose-200/80 bg-rose-900/10 border border-rose-500/20 p-3 rounded-lg">{data.mistakes}</p>
                          </div>
                      )}
                  </div>
              )}
              
              {/* Bottom Spacer */}
              <div className="h-16"></div>
          </div>
      );

      // 3. Mobile Practice Mode
      const MobilePracticeView = () => (
          <div className="flex-1 flex flex-col bg-slate-950 min-h-0">
              {/* Toolbar */}
              <div className="h-12 border-b border-white/10 flex items-center justify-between px-4 bg-white/5 shrink-0">
                  <select 
                      value={data.solutions[activeSolIndex]?.language || 'javascript'} 
                      onChange={(e) => { const s = [...data.solutions]; s[activeSolIndex].language = e.target.value; setData({...data, solutions:s}); }} 
                      className="bg-black/40 border border-white/10 text-xs font-bold text-slate-300 rounded-lg px-2 py-1.5 focus:outline-none"
                  >
                      <option value="javascript">JS</option>
                      <option value="python">Py</option>
                      <option value="java">Java</option>
                  </select>
                  <div className="flex items-center gap-2">
                      <button 
                        onClick={handleSmartCoach} 
                        disabled={!!aiStatus || isMetadataMissing}
                        className="p-1.5 bg-purple-600/20 text-purple-300 rounded hover:bg-purple-600/30 disabled:opacity-50" 
                        title="AI Coach"
                      >
                        <BrainCircuit size={16}/>
                      </button>
                      <button onClick={() => setIsConsoleOpen(!isConsoleOpen)} className={`p-1.5 rounded transition-colors ${isConsoleOpen ? 'bg-indigo-600 text-white' : 'text-slate-400 hover:bg-white/10'}`}><Terminal size={16}/></button>
                  </div>
              </div>

              {/* Editor */}
              <div className={`flex-1 relative min-h-0 ${isConsoleOpen ? 'h-[50%]' : 'h-full'}`}>
                  <CodeEditor 
                      code={data.solutions[activeSolIndex]?.code || ''} 
                      onChange={(val) => { const newSols = [...data.solutions]; newSols[activeSolIndex].code = val; setData({...data, solutions: newSols}); }} 
                      language={data.solutions[activeSolIndex]?.language}
                  />
              </div>

              {/* Console Overlay/Split */}
              {isConsoleOpen && (
                  <div className="h-[40%] border-t border-white/10 bg-slate-900 flex flex-col">
                      <div className="flex items-center justify-between px-3 py-2 border-b border-white/5">
                          <span className="text-xs font-bold text-white uppercase">Console</span>
                          <button onClick={() => setIsConsoleOpen(false)}><ChevronDown size={14} className="text-slate-500"/></button>
                      </div>
                      <div className="flex-1 overflow-auto">
                          <Console results={testResults} isOpen={true} onToggle={()=>{}} />
                      </div>
                  </div>
              )}

              {/* Run Bar */}
              <div className="p-4 border-t border-white/10 bg-slate-900 shrink-0">
                  <button 
                      onClick={handleRunCode} 
                      disabled={isRunningCode || isMetadataMissing}
                      title={getDisabledReason("Run code")}
                      className="w-full py-3 bg-emerald-600 hover:bg-emerald-500 text-white text-sm font-bold rounded-xl flex items-center justify-center gap-2 shadow-lg shadow-emerald-900/20 transition-all active:scale-[0.98] disabled:opacity-50 disabled:cursor-not-allowed"
                  >
                      {isRunningCode ? <Loader2 size={16} className="animate-spin" /> : <PlayCircle size={16} />} 
                      Run Code
                  </button>
              </div>
          </div>
      );

      return (
          <div className="flex flex-col h-full bg-slate-950">
              <MobileHeader />
              {mobileReadOnly ? <MobileReadingView /> : <MobilePracticeView />}
          </div>
      );
  };

  return (
      <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm p-4 animate-in fade-in duration-200" onClick={handleSafeClose}>
          <div className={`${modalBaseStyle} w-full max-w-[95vw] h-[95vh] rounded-2xl flex flex-col overflow-hidden pointer-events-auto shadow-2xl`} onClick={(e) => e.stopPropagation()}>
              {confirmation.type && <ConfirmationDialog />}
              
              {isMobile ? renderMobileLayout() : renderDesktopSplitView()}

              {/* Footer Actions (Desktop Only) */}
              {!isMobile && (
                  <div className={`h-16 ${footerStyle} border-t px-6 flex items-center justify-between shrink-0 bg-slate-900`}>
                        <div className="flex items-center gap-3">
                            <button onClick={requestReset} className="px-4 py-2 rounded-lg font-bold text-xs bg-white/5 text-slate-400 hover:text-white transition-colors flex items-center gap-2 border border-white/5" title="Reset all progress for this question"><RotateCcw size={14} /> Reset</button>
                            <div className="h-6 w-px bg-white/10 mx-1"></div>
                            {data.title && (
                                <div className="flex bg-black/40 p-1 rounded-lg border border-white/5 shadow-inner">
                                    {['Todo', 'Attempted', 'Solved'].map(s => (
                                        <button key={s} onClick={() => setData({...data, status: s as any})} className={`px-3 py-1.5 rounded-md text-xs font-bold transition-all flex items-center gap-1.5 ${data.status === s ? (s === 'Solved' ? 'bg-emerald-900/40 text-emerald-200' : s === 'Attempted' ? 'bg-amber-900/40 text-amber-200' : 'bg-slate-700 text-white') : 'text-slate-500 hover:text-slate-300'}`}>
                                            {s}
                                        </button>
                                    ))}
                                </div>
                            )}
                        </div>
                        <div className="flex items-center gap-3">
                            <button onClick={handleSafeClose} className="px-6 py-2 text-slate-400 font-bold text-sm hover:text-white" title="Close without saving">Cancel</button>
                            <button 
                                onClick={handleSaveWrapper} 
                                disabled={!data.title || !!aiStatus} 
                                title={!data.title ? "Enter a title to save" : "Save Changes"}
                                className="px-6 py-2 bg-indigo-600 text-white rounded-lg font-bold text-sm hover:bg-indigo-500 shadow-lg shadow-indigo-900/50 flex items-center gap-2 disabled:opacity-50 border border-indigo-500"
                            >
                                <Save size={16} /> Save
                            </button>
                        </div>
                    </div>
              )}
          </div>
      </div>
  );
};

export default QuestionModal;